Update pyproject.toml
After recent updates in OpenSSL the MCP server is broken:

`AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?`

Easy fix is to use snowflake connector >= 3.15.0